pipeline {
    agent any

    stages {
        stage('Build Dockerimage') {
            steps{
                dir('WebUIAPI') {
                    // FastAPI 애플리케이션을 도커 이미지로 빌드
                    script {
                        sh 'cd /var/jenkins_home/workspace/backend-fastAPI/WebUIAPI'
                        sh 'ls'
                        sh 'docker build -t freepjt:0.5 -f Dockerfile.Dockerfile .'
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                dir('WebUIAPI') {
                    sh '''
		docker stop freepjt
		docker rm freepjt
		docker container run -d -p 8082:8000 --name freepjt freepjt:0.5
		docker images -f "dangling=true" -q | xargs -r docker rmi
		'''
                }
            }
        }
    }
    post {
        success {
            // 빌드 성공 시 실행되는 코드 (예: 알림 전송, 기타 작업 등)
            echo 'Deployment successful!'
        }

        failure {
            // 빌드 실패 시 실행되는 코드 (예: 알림 전송, 로그 수집 등)
            echo 'Deployment failed!'
        }
    }
}